2019-01-10 11:00:25,581 INFO usb_comm 74: attempting connection
2019-01-10 11:00:25,582 INFO usb_comm 223: Device not found
2019-01-10 11:00:25,582 INFO usb_comm 84: not found
2019-01-10 11:00:25,657 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:00:25,707 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:00:26,819 INFO usb_comm 542: Device not connected
2019-01-10 11:00:26,819 INFO amp_gui 199: failed connection
2019-01-10 11:00:26,829 INFO usb_comm 542: Device not connected
2019-01-10 11:00:26,829 INFO amp_gui 199: failed connection
2019-01-10 11:00:26,930 INFO usb_comm 542: Device not connected
2019-01-10 11:00:26,930 INFO amp_gui 199: failed connection
2019-01-10 11:00:27,105 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:00:27,148 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:00:28,155 INFO usb_comm 542: Device not connected
2019-01-10 11:00:28,155 INFO amp_gui 199: failed connection
2019-01-10 11:00:28,165 INFO usb_comm 542: Device not connected
2019-01-10 11:00:28,165 INFO amp_gui 199: failed connection
2019-01-10 11:00:28,266 INFO usb_comm 542: Device not connected
2019-01-10 11:00:28,266 INFO amp_gui 199: failed connection
2019-01-10 11:15:17,707 INFO usb_comm 74: attempting connection
2019-01-10 11:15:17,709 INFO usb_comm 223: Device not found
2019-01-10 11:15:17,709 INFO usb_comm 84: not found
2019-01-10 11:15:17,786 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:15:17,838 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:15:18,940 INFO usb_comm 542: Device not connected
2019-01-10 11:15:18,940 INFO amp_gui 199: failed connection
2019-01-10 11:15:18,957 INFO usb_comm 542: Device not connected
2019-01-10 11:15:18,959 INFO amp_gui 199: failed connection
2019-01-10 11:15:19,059 INFO usb_comm 542: Device not connected
2019-01-10 11:15:19,059 INFO amp_gui 199: failed connection
2019-01-10 11:15:19,260 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:15:19,338 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:15:20,407 INFO usb_comm 542: Device not connected
2019-01-10 11:15:20,407 INFO amp_gui 199: failed connection
2019-01-10 11:15:20,417 INFO usb_comm 542: Device not connected
2019-01-10 11:15:20,417 INFO amp_gui 199: failed connection
2019-01-10 11:15:20,516 INFO usb_comm 542: Device not connected
2019-01-10 11:15:20,516 INFO amp_gui 199: failed connection
2019-01-10 11:16:32,651 INFO usb_comm 74: attempting connection
2019-01-10 11:16:32,653 INFO usb_comm 223: Device not found
2019-01-10 11:16:32,653 INFO usb_comm 84: not found
2019-01-10 11:16:32,653 INFO amp_gui 196: No Device detected
2019-01-10 11:21:03,171 INFO usb_comm 74: attempting connection
2019-01-10 11:21:03,171 INFO usb_comm 223: Device not found
2019-01-10 11:21:03,171 INFO usb_comm 84: not found
2019-01-10 11:21:03,249 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:21:03,302 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:21:04,420 INFO usb_comm 542: Device not connected
2019-01-10 11:21:04,420 INFO amp_gui 199: failed connection
2019-01-10 11:21:04,430 INFO usb_comm 542: Device not connected
2019-01-10 11:21:04,430 INFO amp_gui 199: failed connection
2019-01-10 11:21:04,530 INFO usb_comm 542: Device not connected
2019-01-10 11:21:04,530 INFO amp_gui 199: failed connection
2019-01-10 11:21:04,703 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:21:04,747 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:21:05,756 INFO usb_comm 542: Device not connected
2019-01-10 11:21:05,756 INFO amp_gui 199: failed connection
2019-01-10 11:21:05,766 INFO usb_comm 542: Device not connected
2019-01-10 11:21:05,766 INFO amp_gui 199: failed connection
2019-01-10 11:21:05,867 INFO usb_comm 542: Device not connected
2019-01-10 11:21:05,867 INFO amp_gui 199: failed connection
2019-01-10 11:25:10,367 INFO usb_comm 74: attempting connection
2019-01-10 11:25:10,367 INFO usb_comm 223: Device not found
2019-01-10 11:25:10,368 INFO usb_comm 84: not found
2019-01-10 11:25:10,450 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:25:10,505 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:25:11,615 INFO usb_comm 542: Device not connected
2019-01-10 11:25:11,615 INFO amp_gui 199: failed connection
2019-01-10 11:25:11,627 INFO usb_comm 542: Device not connected
2019-01-10 11:25:11,627 INFO amp_gui 199: failed connection
2019-01-10 11:25:11,727 INFO usb_comm 542: Device not connected
2019-01-10 11:25:11,727 INFO amp_gui 199: failed connection
2019-01-10 11:25:11,908 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:25:11,953 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:25:12,967 INFO usb_comm 542: Device not connected
2019-01-10 11:25:12,967 INFO amp_gui 199: failed connection
2019-01-10 11:25:12,976 INFO usb_comm 542: Device not connected
2019-01-10 11:25:12,976 INFO amp_gui 199: failed connection
2019-01-10 11:25:13,076 INFO usb_comm 542: Device not connected
2019-01-10 11:25:13,076 INFO amp_gui 199: failed connection
2019-01-10 11:25:56,555 INFO usb_comm 74: attempting connection
2019-01-10 11:25:56,555 INFO usb_comm 223: Device not found
2019-01-10 11:25:56,555 INFO usb_comm 84: not found
2019-01-10 11:27:42,868 INFO usb_comm 74: attempting connection
2019-01-10 11:27:42,868 INFO usb_comm 223: Device not found
2019-01-10 11:27:42,869 INFO usb_comm 84: not found
2019-01-10 11:27:42,944 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:27:42,994 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:27:44,105 INFO usb_comm 542: Device not connected
2019-01-10 11:27:44,105 INFO amp_gui 199: failed connection
2019-01-10 11:27:44,115 INFO usb_comm 542: Device not connected
2019-01-10 11:27:44,115 INFO amp_gui 199: failed connection
2019-01-10 11:27:44,216 INFO usb_comm 542: Device not connected
2019-01-10 11:27:44,216 INFO amp_gui 199: failed connection
2019-01-10 11:27:44,390 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:27:44,433 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:27:45,441 INFO usb_comm 542: Device not connected
2019-01-10 11:27:45,441 INFO amp_gui 199: failed connection
2019-01-10 11:27:45,453 INFO usb_comm 542: Device not connected
2019-01-10 11:27:45,453 INFO amp_gui 199: failed connection
2019-01-10 11:27:45,552 INFO usb_comm 542: Device not connected
2019-01-10 11:27:45,552 INFO amp_gui 199: failed connection
2019-01-10 11:31:35,145 INFO usb_comm 74: attempting connection
2019-01-10 11:31:35,145 INFO usb_comm 223: Device not found
2019-01-10 11:31:35,145 INFO usb_comm 84: not found
2019-01-10 11:31:35,221 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:31:35,273 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:31:36,388 INFO usb_comm 542: Device not connected
2019-01-10 11:31:36,388 INFO amp_gui 199: failed connection
2019-01-10 11:31:36,398 INFO usb_comm 542: Device not connected
2019-01-10 11:31:36,398 INFO amp_gui 199: failed connection
2019-01-10 11:31:36,499 INFO usb_comm 542: Device not connected
2019-01-10 11:31:36,499 INFO amp_gui 199: failed connection
2019-01-10 11:31:36,671 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:31:36,713 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:31:37,721 INFO usb_comm 542: Device not connected
2019-01-10 11:31:37,721 INFO amp_gui 199: failed connection
2019-01-10 11:31:37,732 INFO usb_comm 542: Device not connected
2019-01-10 11:31:37,732 INFO amp_gui 199: failed connection
2019-01-10 11:31:37,832 INFO usb_comm 542: Device not connected
2019-01-10 11:31:37,832 INFO amp_gui 199: failed connection
2019-01-10 11:31:50,704 INFO usb_comm 74: attempting connection
2019-01-10 11:31:50,704 INFO usb_comm 223: Device not found
2019-01-10 11:31:50,704 INFO usb_comm 84: not found
2019-01-10 11:31:50,706 INFO amp_gui 196: No Device detected
2019-01-10 11:37:21,782 INFO usb_comm 74: attempting connection
2019-01-10 11:37:21,782 INFO usb_comm 223: Device not found
2019-01-10 11:37:21,783 INFO usb_comm 84: not found
2019-01-10 11:37:21,862 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:37:21,914 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:37:23,043 INFO usb_comm 542: Device not connected
2019-01-10 11:37:23,043 INFO amp_gui 199: failed connection
2019-01-10 11:37:23,055 INFO usb_comm 542: Device not connected
2019-01-10 11:37:23,055 INFO amp_gui 199: failed connection
2019-01-10 11:37:23,154 INFO usb_comm 542: Device not connected
2019-01-10 11:37:23,155 INFO amp_gui 199: failed connection
2019-01-10 11:37:23,355 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:37:23,408 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:37:24,430 INFO usb_comm 542: Device not connected
2019-01-10 11:37:24,430 INFO amp_gui 199: failed connection
2019-01-10 11:37:24,440 INFO usb_comm 542: Device not connected
2019-01-10 11:37:24,440 INFO amp_gui 199: failed connection
2019-01-10 11:37:24,540 INFO usb_comm 542: Device not connected
2019-01-10 11:37:24,540 INFO amp_gui 199: failed connection
2019-01-10 11:38:37,009 INFO usb_comm 74: attempting connection
2019-01-10 11:38:37,010 INFO usb_comm 223: Device not found
2019-01-10 11:38:37,010 INFO usb_comm 84: not found
2019-01-10 11:38:37,010 INFO amp_gui 196: No Device detected
2019-01-10 11:40:37,865 INFO usb_comm 74: attempting connection
2019-01-10 11:40:37,865 INFO usb_comm 223: Device not found
2019-01-10 11:40:37,865 INFO usb_comm 84: not found
2019-01-10 11:40:37,865 INFO amp_gui 196: No Device detected
2019-01-10 11:42:20,763 INFO usb_comm 74: attempting connection
2019-01-10 11:42:20,763 INFO usb_comm 223: Device not found
2019-01-10 11:42:20,763 INFO usb_comm 84: not found
2019-01-10 11:42:20,842 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:42:20,897 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:42:22,009 INFO usb_comm 542: Device not connected
2019-01-10 11:42:22,009 INFO amp_gui 199: failed connection
2019-01-10 11:42:22,019 INFO usb_comm 542: Device not connected
2019-01-10 11:42:22,019 INFO amp_gui 199: failed connection
2019-01-10 11:42:22,118 INFO usb_comm 542: Device not connected
2019-01-10 11:42:22,118 INFO amp_gui 199: failed connection
2019-01-10 11:42:22,290 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:42:22,332 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:42:23,339 INFO usb_comm 542: Device not connected
2019-01-10 11:42:23,339 INFO amp_gui 199: failed connection
2019-01-10 11:42:23,349 INFO usb_comm 542: Device not connected
2019-01-10 11:42:23,349 INFO amp_gui 199: failed connection
2019-01-10 11:42:23,450 INFO usb_comm 542: Device not connected
2019-01-10 11:42:23,450 INFO amp_gui 199: failed connection
2019-01-10 11:43:20,721 INFO usb_comm 74: attempting connection
2019-01-10 11:43:20,721 INFO usb_comm 223: Device not found
2019-01-10 11:43:20,721 INFO usb_comm 84: not found
2019-01-10 11:43:20,798 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:43:20,848 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:43:21,953 INFO usb_comm 542: Device not connected
2019-01-10 11:43:21,953 INFO amp_gui 199: failed connection
2019-01-10 11:43:21,964 INFO usb_comm 542: Device not connected
2019-01-10 11:43:21,966 INFO amp_gui 199: failed connection
2019-01-10 11:43:22,066 INFO usb_comm 542: Device not connected
2019-01-10 11:43:22,066 INFO amp_gui 199: failed connection
2019-01-10 11:43:22,243 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:43:22,286 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:43:23,296 INFO usb_comm 542: Device not connected
2019-01-10 11:43:23,296 INFO amp_gui 199: failed connection
2019-01-10 11:43:23,305 INFO usb_comm 542: Device not connected
2019-01-10 11:43:23,305 INFO amp_gui 199: failed connection
2019-01-10 11:43:23,405 INFO usb_comm 542: Device not connected
2019-01-10 11:43:23,405 INFO amp_gui 199: failed connection
2019-01-10 11:45:06,335 INFO usb_comm 74: attempting connection
2019-01-10 11:45:06,335 INFO usb_comm 223: Device not found
2019-01-10 11:45:06,335 INFO usb_comm 84: not found
2019-01-10 11:45:06,413 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:45:06,463 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:45:07,573 INFO usb_comm 542: Device not connected
2019-01-10 11:45:07,573 INFO amp_gui 199: failed connection
2019-01-10 11:45:07,584 INFO usb_comm 542: Device not connected
2019-01-10 11:45:07,584 INFO amp_gui 199: failed connection
2019-01-10 11:45:07,684 INFO usb_comm 542: Device not connected
2019-01-10 11:45:07,684 INFO amp_gui 199: failed connection
2019-01-10 11:45:07,865 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:45:07,911 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:45:08,926 INFO usb_comm 542: Device not connected
2019-01-10 11:45:08,926 INFO amp_gui 199: failed connection
2019-01-10 11:45:08,937 INFO usb_comm 542: Device not connected
2019-01-10 11:45:08,937 INFO amp_gui 199: failed connection
2019-01-10 11:45:09,036 INFO usb_comm 542: Device not connected
2019-01-10 11:45:09,036 INFO amp_gui 199: failed connection
2019-01-10 11:46:19,015 INFO usb_comm 74: attempting connection
2019-01-10 11:46:19,016 INFO usb_comm 223: Device not found
2019-01-10 11:46:19,016 INFO usb_comm 84: not found
2019-01-10 11:46:19,107 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:46:19,164 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:46:20,292 INFO usb_comm 542: Device not connected
2019-01-10 11:46:20,292 INFO amp_gui 199: failed connection
2019-01-10 11:46:20,302 INFO usb_comm 542: Device not connected
2019-01-10 11:46:20,302 INFO amp_gui 199: failed connection
2019-01-10 11:46:20,403 INFO usb_comm 542: Device not connected
2019-01-10 11:46:20,403 INFO amp_gui 199: failed connection
2019-01-10 11:46:20,578 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:46:20,619 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:46:21,628 INFO usb_comm 542: Device not connected
2019-01-10 11:46:21,628 INFO amp_gui 199: failed connection
2019-01-10 11:46:21,638 INFO usb_comm 542: Device not connected
2019-01-10 11:46:21,638 INFO amp_gui 199: failed connection
2019-01-10 11:46:21,739 INFO usb_comm 542: Device not connected
2019-01-10 11:46:21,739 INFO amp_gui 199: failed connection
2019-01-10 11:48:09,213 INFO usb_comm 74: attempting connection
2019-01-10 11:48:09,214 INFO usb_comm 223: Device not found
2019-01-10 11:48:09,216 INFO usb_comm 84: not found
2019-01-10 11:48:09,292 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:48:09,342 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:48:10,460 INFO usb_comm 542: Device not connected
2019-01-10 11:48:10,460 INFO amp_gui 199: failed connection
2019-01-10 11:48:10,470 INFO usb_comm 542: Device not connected
2019-01-10 11:48:10,470 INFO amp_gui 199: failed connection
2019-01-10 11:48:10,571 INFO usb_comm 542: Device not connected
2019-01-10 11:48:10,571 INFO amp_gui 199: failed connection
2019-01-10 11:48:10,785 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:48:10,835 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:48:11,861 INFO usb_comm 542: Device not connected
2019-01-10 11:48:11,861 INFO amp_gui 199: failed connection
2019-01-10 11:48:11,871 INFO usb_comm 542: Device not connected
2019-01-10 11:48:11,871 INFO amp_gui 199: failed connection
2019-01-10 11:48:11,973 INFO usb_comm 542: Device not connected
2019-01-10 11:48:11,973 INFO amp_gui 199: failed connection
2019-01-10 11:48:19,910 INFO usb_comm 74: attempting connection
2019-01-10 11:48:19,911 INFO usb_comm 223: Device not found
2019-01-10 11:48:19,911 INFO usb_comm 84: not found
2019-01-10 11:48:19,911 INFO amp_gui 196: No Device detected
2019-01-10 11:48:54,756 INFO usb_comm 74: attempting connection
2019-01-10 11:48:54,756 INFO usb_comm 223: Device not found
2019-01-10 11:48:54,756 INFO usb_comm 84: not found
2019-01-10 11:48:54,836 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:48:54,890 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:48:56,007 INFO usb_comm 542: Device not connected
2019-01-10 11:48:56,007 INFO amp_gui 199: failed connection
2019-01-10 11:48:56,017 INFO usb_comm 542: Device not connected
2019-01-10 11:48:56,017 INFO amp_gui 199: failed connection
2019-01-10 11:48:56,118 INFO usb_comm 542: Device not connected
2019-01-10 11:48:56,118 INFO amp_gui 199: failed connection
2019-01-10 11:48:56,296 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:48:56,339 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:48:57,351 INFO usb_comm 542: Device not connected
2019-01-10 11:48:57,351 INFO amp_gui 199: failed connection
2019-01-10 11:48:57,361 INFO usb_comm 542: Device not connected
2019-01-10 11:48:57,361 INFO amp_gui 199: failed connection
2019-01-10 11:48:57,463 INFO usb_comm 542: Device not connected
2019-01-10 11:48:57,463 INFO amp_gui 199: failed connection
2019-01-10 11:49:01,494 INFO usb_comm 74: attempting connection
2019-01-10 11:49:01,494 INFO usb_comm 223: Device not found
2019-01-10 11:49:01,494 INFO usb_comm 84: not found
2019-01-10 11:49:01,494 INFO amp_gui 196: No Device detected
2019-01-10 11:50:38,259 INFO usb_comm 74: attempting connection
2019-01-10 11:50:38,259 INFO usb_comm 223: Device not found
2019-01-10 11:50:38,259 INFO usb_comm 84: not found
2019-01-10 11:50:38,341 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:50:38,392 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:50:39,500 INFO usb_comm 542: Device not connected
2019-01-10 11:50:39,500 INFO amp_gui 199: failed connection
2019-01-10 11:50:39,509 INFO usb_comm 542: Device not connected
2019-01-10 11:50:39,509 INFO amp_gui 199: failed connection
2019-01-10 11:50:39,609 INFO usb_comm 542: Device not connected
2019-01-10 11:50:39,609 INFO amp_gui 199: failed connection
2019-01-10 11:50:39,782 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:50:39,826 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:50:40,835 INFO usb_comm 542: Device not connected
2019-01-10 11:50:40,835 INFO amp_gui 199: failed connection
2019-01-10 11:50:40,845 INFO usb_comm 542: Device not connected
2019-01-10 11:50:40,845 INFO amp_gui 199: failed connection
2019-01-10 11:50:40,944 INFO usb_comm 542: Device not connected
2019-01-10 11:50:40,944 INFO amp_gui 199: failed connection
2019-01-10 11:50:46,746 INFO usb_comm 74: attempting connection
2019-01-10 11:50:46,746 INFO usb_comm 223: Device not found
2019-01-10 11:50:46,746 INFO usb_comm 84: not found
2019-01-10 11:50:46,746 INFO amp_gui 196: No Device detected
2019-01-10 11:51:36,242 INFO usb_comm 74: attempting connection
2019-01-10 11:51:36,243 INFO usb_comm 223: Device not found
2019-01-10 11:51:36,243 INFO usb_comm 84: not found
2019-01-10 11:51:36,318 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:51:36,367 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:51:37,473 INFO usb_comm 542: Device not connected
2019-01-10 11:51:37,473 INFO amp_gui 199: failed connection
2019-01-10 11:51:37,484 INFO usb_comm 542: Device not connected
2019-01-10 11:51:37,484 INFO amp_gui 199: failed connection
2019-01-10 11:51:37,585 INFO usb_comm 542: Device not connected
2019-01-10 11:51:37,585 INFO amp_gui 199: failed connection
2019-01-10 11:51:37,759 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:51:37,802 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:51:38,811 INFO usb_comm 542: Device not connected
2019-01-10 11:51:38,811 INFO amp_gui 199: failed connection
2019-01-10 11:51:38,821 INFO usb_comm 542: Device not connected
2019-01-10 11:51:38,821 INFO amp_gui 199: failed connection
2019-01-10 11:51:38,921 INFO usb_comm 542: Device not connected
2019-01-10 11:51:38,921 INFO amp_gui 199: failed connection
2019-01-10 11:51:48,966 INFO usb_comm 74: attempting connection
2019-01-10 11:51:48,966 INFO usb_comm 223: Device not found
2019-01-10 11:51:48,966 INFO usb_comm 84: not found
2019-01-10 11:51:48,966 INFO amp_gui 196: No Device detected
2019-01-10 11:52:21,211 INFO usb_comm 74: attempting connection
2019-01-10 11:52:21,213 INFO usb_comm 223: Device not found
2019-01-10 11:52:21,213 INFO usb_comm 84: not found
2019-01-10 11:52:21,288 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:52:21,336 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:52:22,447 INFO usb_comm 542: Device not connected
2019-01-10 11:52:22,447 INFO amp_gui 199: failed connection
2019-01-10 11:52:22,459 INFO usb_comm 542: Device not connected
2019-01-10 11:52:22,459 INFO amp_gui 199: failed connection
2019-01-10 11:52:22,559 INFO usb_comm 542: Device not connected
2019-01-10 11:52:22,559 INFO amp_gui 199: failed connection
2019-01-10 11:52:22,733 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:52:22,776 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:52:23,782 INFO usb_comm 542: Device not connected
2019-01-10 11:52:23,782 INFO amp_gui 199: failed connection
2019-01-10 11:52:23,792 INFO usb_comm 542: Device not connected
2019-01-10 11:52:23,792 INFO amp_gui 199: failed connection
2019-01-10 11:52:23,892 INFO usb_comm 542: Device not connected
2019-01-10 11:52:23,892 INFO amp_gui 199: failed connection
2019-01-10 11:52:41,459 INFO usb_comm 74: attempting connection
2019-01-10 11:52:41,460 INFO usb_comm 223: Device not found
2019-01-10 11:52:41,460 INFO usb_comm 84: not found
2019-01-10 11:52:41,460 INFO amp_gui 196: No Device detected
2019-01-10 11:52:45,414 INFO usb_comm 74: attempting connection
2019-01-10 11:52:45,414 INFO usb_comm 223: Device not found
2019-01-10 11:52:45,414 INFO usb_comm 84: not found
2019-01-10 11:52:45,414 INFO amp_gui 196: No Device detected
2019-01-10 11:53:48,223 INFO usb_comm 74: attempting connection
2019-01-10 11:53:48,224 INFO usb_comm 223: Device not found
2019-01-10 11:53:48,224 INFO usb_comm 84: not found
2019-01-10 11:53:48,299 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:53:48,351 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:53:49,457 INFO usb_comm 542: Device not connected
2019-01-10 11:53:49,457 INFO amp_gui 199: failed connection
2019-01-10 11:53:49,467 INFO usb_comm 542: Device not connected
2019-01-10 11:53:49,467 INFO amp_gui 199: failed connection
2019-01-10 11:53:49,568 INFO usb_comm 542: Device not connected
2019-01-10 11:53:49,569 INFO amp_gui 199: failed connection
2019-01-10 11:53:49,747 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:53:49,792 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:53:50,802 INFO usb_comm 542: Device not connected
2019-01-10 11:53:50,802 INFO amp_gui 199: failed connection
2019-01-10 11:53:50,812 INFO usb_comm 542: Device not connected
2019-01-10 11:53:50,812 INFO amp_gui 199: failed connection
2019-01-10 11:53:50,914 INFO usb_comm 542: Device not connected
2019-01-10 11:53:50,914 INFO amp_gui 199: failed connection
2019-01-10 11:54:27,513 INFO usb_comm 74: attempting connection
2019-01-10 11:54:27,513 INFO usb_comm 223: Device not found
2019-01-10 11:54:27,513 INFO usb_comm 84: not found
2019-01-10 11:54:27,595 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:54:27,648 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:54:28,757 INFO usb_comm 542: Device not connected
2019-01-10 11:54:28,757 INFO amp_gui 199: failed connection
2019-01-10 11:54:28,767 INFO usb_comm 542: Device not connected
2019-01-10 11:54:28,767 INFO amp_gui 199: failed connection
2019-01-10 11:54:28,868 INFO usb_comm 542: Device not connected
2019-01-10 11:54:28,868 INFO amp_gui 199: failed connection
2019-01-10 11:54:29,049 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:54:29,092 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:54:30,105 INFO usb_comm 542: Device not connected
2019-01-10 11:54:30,105 INFO amp_gui 199: failed connection
2019-01-10 11:54:30,115 INFO usb_comm 542: Device not connected
2019-01-10 11:54:30,115 INFO amp_gui 199: failed connection
2019-01-10 11:54:30,216 INFO usb_comm 542: Device not connected
2019-01-10 11:54:30,216 INFO amp_gui 199: failed connection
2019-01-10 11:56:43,055 INFO usb_comm 74: attempting connection
2019-01-10 11:56:43,055 INFO usb_comm 223: Device not found
2019-01-10 11:56:43,055 INFO usb_comm 84: not found
2019-01-10 11:56:43,134 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:56:43,184 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:56:44,296 INFO usb_comm 542: Device not connected
2019-01-10 11:56:44,296 INFO amp_gui 199: failed connection
2019-01-10 11:56:44,306 INFO usb_comm 542: Device not connected
2019-01-10 11:56:44,306 INFO amp_gui 199: failed connection
2019-01-10 11:56:44,407 INFO usb_comm 542: Device not connected
2019-01-10 11:56:44,407 INFO amp_gui 199: failed connection
2019-01-10 11:56:44,588 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:56:44,634 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:56:45,651 INFO usb_comm 542: Device not connected
2019-01-10 11:56:45,651 INFO amp_gui 199: failed connection
2019-01-10 11:56:45,661 INFO usb_comm 542: Device not connected
2019-01-10 11:56:45,661 INFO amp_gui 199: failed connection
2019-01-10 11:56:45,762 INFO usb_comm 542: Device not connected
2019-01-10 11:56:45,762 INFO amp_gui 199: failed connection
2019-01-10 11:57:38,246 INFO usb_comm 74: attempting connection
2019-01-10 11:57:38,246 INFO usb_comm 223: Device not found
2019-01-10 11:57:38,246 INFO usb_comm 84: not found
2019-01-10 11:57:38,328 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 11:57:38,384 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:57:39,490 INFO usb_comm 542: Device not connected
2019-01-10 11:57:39,490 INFO amp_gui 199: failed connection
2019-01-10 11:57:39,500 INFO usb_comm 542: Device not connected
2019-01-10 11:57:39,500 INFO amp_gui 199: failed connection
2019-01-10 11:57:39,601 INFO usb_comm 542: Device not connected
2019-01-10 11:57:39,601 INFO amp_gui 199: failed connection
2019-01-10 11:57:39,778 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 11:57:39,823 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 11:57:40,838 INFO usb_comm 542: Device not connected
2019-01-10 11:57:40,838 INFO amp_gui 199: failed connection
2019-01-10 11:57:40,848 INFO usb_comm 542: Device not connected
2019-01-10 11:57:40,848 INFO amp_gui 199: failed connection
2019-01-10 11:57:40,950 INFO usb_comm 542: Device not connected
2019-01-10 11:57:40,950 INFO amp_gui 199: failed connection
2019-01-10 12:41:45,042 INFO usb_comm 74: attempting connection
2019-01-10 12:41:45,042 INFO usb_comm 223: Device not found
2019-01-10 12:41:45,042 INFO usb_comm 84: not found
2019-01-10 12:41:45,148 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:41:45,214 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:41:46,344 INFO usb_comm 542: Device not connected
2019-01-10 12:41:46,344 INFO amp_gui 199: failed connection
2019-01-10 12:41:46,355 INFO usb_comm 542: Device not connected
2019-01-10 12:41:46,355 INFO amp_gui 199: failed connection
2019-01-10 12:41:46,456 INFO usb_comm 542: Device not connected
2019-01-10 12:41:46,456 INFO amp_gui 199: failed connection
2019-01-10 12:41:46,628 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:41:46,673 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:41:47,680 INFO usb_comm 542: Device not connected
2019-01-10 12:41:47,680 INFO amp_gui 199: failed connection
2019-01-10 12:41:47,690 INFO usb_comm 542: Device not connected
2019-01-10 12:41:47,690 INFO amp_gui 199: failed connection
2019-01-10 12:41:47,792 INFO usb_comm 542: Device not connected
2019-01-10 12:41:47,792 INFO amp_gui 199: failed connection
2019-01-10 12:45:42,141 INFO usb_comm 74: attempting connection
2019-01-10 12:45:43,079 INFO usb_comm 223: Device not found
2019-01-10 12:45:43,081 INFO usb_comm 84: not found
2019-01-10 12:45:43,163 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:45:43,214 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:45:44,428 INFO usb_comm 542: Device not connected
2019-01-10 12:45:44,428 INFO amp_gui 201: failed connection
2019-01-10 12:45:44,440 INFO usb_comm 542: Device not connected
2019-01-10 12:45:44,440 INFO amp_gui 201: failed connection
2019-01-10 12:45:44,539 INFO usb_comm 542: Device not connected
2019-01-10 12:45:44,539 INFO amp_gui 201: failed connection
2019-01-10 12:45:44,719 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:45:44,763 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:45:45,901 INFO usb_comm 542: Device not connected
2019-01-10 12:45:45,901 INFO amp_gui 201: failed connection
2019-01-10 12:45:45,911 INFO usb_comm 542: Device not connected
2019-01-10 12:45:45,911 INFO amp_gui 201: failed connection
2019-01-10 12:45:46,012 INFO usb_comm 542: Device not connected
2019-01-10 12:45:46,012 INFO amp_gui 201: failed connection
2019-01-10 12:47:15,502 INFO usb_comm 74: attempting connection
2019-01-10 12:47:16,361 INFO usb_comm 223: Device not found
2019-01-10 12:47:16,361 INFO usb_comm 84: not found
2019-01-10 12:47:16,447 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:47:16,503 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:47:17,753 INFO usb_comm 542: Device not connected
2019-01-10 12:47:17,753 INFO amp_gui 201: failed connection
2019-01-10 12:47:17,766 INFO usb_comm 542: Device not connected
2019-01-10 12:47:17,766 INFO amp_gui 201: failed connection
2019-01-10 12:47:17,867 INFO usb_comm 542: Device not connected
2019-01-10 12:47:17,867 INFO amp_gui 201: failed connection
2019-01-10 12:47:18,046 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:47:18,092 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:47:19,273 INFO usb_comm 542: Device not connected
2019-01-10 12:47:19,273 INFO amp_gui 201: failed connection
2019-01-10 12:47:19,283 INFO usb_comm 542: Device not connected
2019-01-10 12:47:19,283 INFO amp_gui 201: failed connection
2019-01-10 12:47:19,384 INFO usb_comm 542: Device not connected
2019-01-10 12:47:19,384 INFO amp_gui 201: failed connection
2019-01-10 12:52:44,089 INFO usb_comm 74: attempting connection
2019-01-10 12:52:45,546 INFO usb_comm 223: Device not found
2019-01-10 12:52:45,546 INFO usb_comm 84: not found
2019-01-10 12:52:45,628 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:52:45,678 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:52:46,898 INFO usb_comm 542: Device not connected
2019-01-10 12:52:46,898 INFO amp_gui 199: failed connection
2019-01-10 12:52:46,910 INFO usb_comm 542: Device not connected
2019-01-10 12:52:46,910 INFO amp_gui 199: failed connection
2019-01-10 12:52:47,009 INFO usb_comm 542: Device not connected
2019-01-10 12:52:47,009 INFO amp_gui 199: failed connection
2019-01-10 12:52:47,188 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:52:47,234 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:52:48,369 INFO usb_comm 542: Device not connected
2019-01-10 12:52:48,369 INFO amp_gui 199: failed connection
2019-01-10 12:52:48,380 INFO usb_comm 542: Device not connected
2019-01-10 12:52:48,380 INFO amp_gui 199: failed connection
2019-01-10 12:52:48,480 INFO usb_comm 542: Device not connected
2019-01-10 12:52:48,480 INFO amp_gui 199: failed connection
2019-01-10 12:53:41,993 INFO usb_comm 74: attempting connection
2019-01-10 12:53:42,546 INFO usb_comm 223: Device not found
2019-01-10 12:53:42,546 INFO usb_comm 84: not found
2019-01-10 12:53:42,628 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:53:42,680 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:53:43,891 INFO usb_comm 542: Device not connected
2019-01-10 12:53:43,891 INFO amp_gui 199: failed connection
2019-01-10 12:53:43,901 INFO usb_comm 542: Device not connected
2019-01-10 12:53:43,901 INFO amp_gui 199: failed connection
2019-01-10 12:53:44,002 INFO usb_comm 542: Device not connected
2019-01-10 12:53:44,002 INFO amp_gui 199: failed connection
2019-01-10 12:53:44,184 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:53:44,227 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:53:45,351 INFO usb_comm 542: Device not connected
2019-01-10 12:53:45,351 INFO amp_gui 199: failed connection
2019-01-10 12:53:45,361 INFO usb_comm 542: Device not connected
2019-01-10 12:53:45,361 INFO amp_gui 199: failed connection
2019-01-10 12:53:45,460 INFO usb_comm 542: Device not connected
2019-01-10 12:53:45,460 INFO amp_gui 199: failed connection
2019-01-10 12:54:39,288 INFO usb_comm 74: attempting connection
2019-01-10 12:54:44,227 INFO usb_comm 223: Device not found
2019-01-10 12:54:44,229 INFO usb_comm 84: not found
2019-01-10 12:54:44,311 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:54:44,361 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:54:45,582 INFO usb_comm 542: Device not connected
2019-01-10 12:54:45,582 INFO amp_gui 199: failed connection
2019-01-10 12:54:45,592 INFO usb_comm 542: Device not connected
2019-01-10 12:54:45,592 INFO amp_gui 199: failed connection
2019-01-10 12:54:45,694 INFO usb_comm 542: Device not connected
2019-01-10 12:54:45,694 INFO amp_gui 199: failed connection
2019-01-10 12:54:45,868 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:54:45,911 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:54:47,039 INFO usb_comm 542: Device not connected
2019-01-10 12:54:47,039 INFO amp_gui 199: failed connection
2019-01-10 12:54:47,049 INFO usb_comm 542: Device not connected
2019-01-10 12:54:47,049 INFO amp_gui 199: failed connection
2019-01-10 12:54:47,150 INFO usb_comm 542: Device not connected
2019-01-10 12:54:47,150 INFO amp_gui 199: failed connection
2019-01-10 12:55:50,115 INFO usb_comm 74: attempting connection
2019-01-10 12:55:51,058 INFO usb_comm 223: Device not found
2019-01-10 12:55:51,059 INFO usb_comm 84: not found
2019-01-10 12:55:51,144 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:55:51,197 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:55:52,427 INFO usb_comm 542: Device not connected
2019-01-10 12:55:52,427 INFO amp_gui 199: failed connection
2019-01-10 12:55:52,437 INFO usb_comm 542: Device not connected
2019-01-10 12:55:52,437 INFO amp_gui 199: failed connection
2019-01-10 12:55:52,539 INFO usb_comm 542: Device not connected
2019-01-10 12:55:52,539 INFO amp_gui 199: failed connection
2019-01-10 12:55:52,710 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 12:55:52,753 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:55:53,875 INFO usb_comm 542: Device not connected
2019-01-10 12:55:53,875 INFO amp_gui 199: failed connection
2019-01-10 12:55:53,885 INFO usb_comm 542: Device not connected
2019-01-10 12:55:53,885 INFO amp_gui 199: failed connection
2019-01-10 12:55:53,986 INFO usb_comm 542: Device not connected
2019-01-10 12:55:53,986 INFO amp_gui 199: failed connection
2019-01-10 12:56:27,164 INFO usb_comm 74: attempting connection
2019-01-10 12:56:32,259 INFO usb_comm 223: Device not found
2019-01-10 12:56:32,259 INFO usb_comm 84: not found
2019-01-10 12:56:32,342 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 12:56:32,394 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:56:35,013 INFO usb_comm 542: Device not connected
2019-01-10 12:56:35,013 INFO amp_gui 199: failed connection
2019-01-10 12:56:35,023 INFO usb_comm 542: Device not connected
2019-01-10 12:56:35,023 INFO amp_gui 199: failed connection
2019-01-10 12:56:35,122 INFO usb_comm 542: Device not connected
2019-01-10 12:56:35,122 INFO amp_gui 199: failed connection
2019-01-10 12:56:35,293 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage19" as iconphoto: not a photo image
2019-01-10 12:56:35,336 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 12:56:36,470 INFO usb_comm 542: Device not connected
2019-01-10 12:56:36,470 INFO amp_gui 199: failed connection
2019-01-10 12:56:36,480 INFO usb_comm 542: Device not connected
2019-01-10 12:56:36,480 INFO amp_gui 199: failed connection
2019-01-10 12:56:36,579 INFO usb_comm 542: Device not connected
2019-01-10 12:56:36,579 INFO amp_gui 199: failed connection
2019-01-10 13:00:27,424 INFO usb_comm 74: attempting connection
2019-01-10 13:00:30,862 INFO usb_comm 223: Device not found
2019-01-10 13:00:30,862 INFO usb_comm 84: not found
2019-01-10 13:00:30,951 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:00:31,003 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:00:32,223 INFO usb_comm 542: Device not connected
2019-01-10 13:00:32,223 INFO amp_gui 200: failed connection
2019-01-10 13:00:32,233 INFO usb_comm 542: Device not connected
2019-01-10 13:00:32,233 INFO amp_gui 200: failed connection
2019-01-10 13:00:32,335 INFO usb_comm 542: Device not connected
2019-01-10 13:00:32,335 INFO amp_gui 200: failed connection
2019-01-10 13:00:32,506 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:00:32,551 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:00:33,674 INFO usb_comm 542: Device not connected
2019-01-10 13:00:33,674 INFO amp_gui 200: failed connection
2019-01-10 13:00:33,686 INFO usb_comm 542: Device not connected
2019-01-10 13:00:33,686 INFO amp_gui 200: failed connection
2019-01-10 13:00:33,786 INFO usb_comm 542: Device not connected
2019-01-10 13:00:33,786 INFO amp_gui 200: failed connection
2019-01-10 13:01:09,697 INFO usb_comm 74: attempting connection
2019-01-10 13:01:13,124 INFO usb_comm 223: Device not found
2019-01-10 13:01:13,124 INFO usb_comm 84: not found
2019-01-10 13:01:13,207 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:01:13,263 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:01:14,493 INFO usb_comm 542: Device not connected
2019-01-10 13:01:14,493 INFO amp_gui 200: failed connection
2019-01-10 13:01:14,503 INFO usb_comm 542: Device not connected
2019-01-10 13:01:14,503 INFO amp_gui 200: failed connection
2019-01-10 13:01:14,604 INFO usb_comm 542: Device not connected
2019-01-10 13:01:14,604 INFO amp_gui 200: failed connection
2019-01-10 13:01:14,776 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:01:14,818 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:01:15,940 INFO usb_comm 542: Device not connected
2019-01-10 13:01:15,940 INFO amp_gui 200: failed connection
2019-01-10 13:01:15,950 INFO usb_comm 542: Device not connected
2019-01-10 13:01:15,950 INFO amp_gui 200: failed connection
2019-01-10 13:01:16,051 INFO usb_comm 542: Device not connected
2019-01-10 13:01:16,051 INFO amp_gui 200: failed connection
2019-01-10 13:12:11,115 INFO usb_comm 74: attempting connection
2019-01-10 13:12:11,117 INFO usb_comm 223: Device not found
2019-01-10 13:12:11,117 INFO usb_comm 84: not found
2019-01-10 13:12:11,193 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:12:11,243 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:12:12,348 INFO usb_comm 542: Device not connected
2019-01-10 13:12:12,348 INFO amp_gui 200: failed connection
2019-01-10 13:12:12,358 INFO usb_comm 542: Device not connected
2019-01-10 13:12:12,358 INFO amp_gui 200: failed connection
2019-01-10 13:12:12,460 INFO usb_comm 542: Device not connected
2019-01-10 13:12:12,460 INFO amp_gui 200: failed connection
2019-01-10 13:12:12,634 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:12:12,678 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:12:13,690 INFO usb_comm 542: Device not connected
2019-01-10 13:12:13,690 INFO amp_gui 200: failed connection
2019-01-10 13:12:13,700 INFO usb_comm 542: Device not connected
2019-01-10 13:12:13,700 INFO amp_gui 200: failed connection
2019-01-10 13:12:13,802 INFO usb_comm 542: Device not connected
2019-01-10 13:12:13,802 INFO amp_gui 200: failed connection
2019-01-10 13:14:05,721 INFO usb_comm 74: attempting connection
2019-01-10 13:14:05,723 INFO usb_comm 223: Device not found
2019-01-10 13:14:05,723 INFO usb_comm 84: not found
2019-01-10 13:14:05,796 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:14:05,845 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:14:06,961 INFO usb_comm 542: Device not connected
2019-01-10 13:14:06,961 INFO amp_gui 200: failed connection
2019-01-10 13:14:06,973 INFO usb_comm 542: Device not connected
2019-01-10 13:14:06,973 INFO amp_gui 200: failed connection
2019-01-10 13:14:07,072 INFO usb_comm 542: Device not connected
2019-01-10 13:14:07,072 INFO amp_gui 200: failed connection
2019-01-10 13:14:07,246 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:14:07,289 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:14:08,296 INFO usb_comm 542: Device not connected
2019-01-10 13:14:08,296 INFO amp_gui 200: failed connection
2019-01-10 13:14:08,306 INFO usb_comm 542: Device not connected
2019-01-10 13:14:08,306 INFO amp_gui 200: failed connection
2019-01-10 13:14:08,407 INFO usb_comm 542: Device not connected
2019-01-10 13:14:08,407 INFO amp_gui 200: failed connection
2019-01-10 13:17:12,058 INFO usb_comm 74: attempting connection
2019-01-10 13:17:12,059 INFO usb_comm 223: Device not found
2019-01-10 13:17:12,059 INFO usb_comm 84: not found
2019-01-10 13:17:12,132 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:17:12,184 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:17:13,283 INFO usb_comm 542: Device not connected
2019-01-10 13:17:13,283 INFO amp_gui 200: failed connection
2019-01-10 13:17:13,295 INFO usb_comm 542: Device not connected
2019-01-10 13:17:13,295 INFO amp_gui 200: failed connection
2019-01-10 13:17:13,394 INFO usb_comm 542: Device not connected
2019-01-10 13:17:13,395 INFO amp_gui 200: failed connection
2019-01-10 13:17:13,572 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:17:13,617 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:17:14,628 INFO usb_comm 542: Device not connected
2019-01-10 13:17:14,628 INFO amp_gui 200: failed connection
2019-01-10 13:17:14,638 INFO usb_comm 542: Device not connected
2019-01-10 13:17:14,638 INFO amp_gui 200: failed connection
2019-01-10 13:17:14,740 INFO usb_comm 542: Device not connected
2019-01-10 13:17:14,740 INFO amp_gui 200: failed connection
2019-01-10 13:17:38,028 INFO usb_comm 74: attempting connection
2019-01-10 13:17:38,028 INFO usb_comm 223: Device not found
2019-01-10 13:17:38,028 INFO usb_comm 84: not found
2019-01-10 13:17:38,101 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:17:38,151 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:17:39,260 INFO usb_comm 542: Device not connected
2019-01-10 13:17:39,260 INFO amp_gui 200: failed connection
2019-01-10 13:17:39,272 INFO usb_comm 542: Device not connected
2019-01-10 13:17:39,272 INFO amp_gui 200: failed connection
2019-01-10 13:17:39,372 INFO usb_comm 542: Device not connected
2019-01-10 13:17:39,372 INFO amp_gui 200: failed connection
2019-01-10 13:17:39,545 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:17:39,588 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:17:40,595 INFO usb_comm 542: Device not connected
2019-01-10 13:17:40,595 INFO amp_gui 200: failed connection
2019-01-10 13:17:40,605 INFO usb_comm 542: Device not connected
2019-01-10 13:17:40,605 INFO amp_gui 200: failed connection
2019-01-10 13:17:40,704 INFO usb_comm 542: Device not connected
2019-01-10 13:17:40,704 INFO amp_gui 200: failed connection
2019-01-10 13:27:27,322 INFO usb_comm 74: attempting connection
2019-01-10 13:27:27,322 INFO usb_comm 223: Device not found
2019-01-10 13:27:27,322 INFO usb_comm 84: not found
2019-01-10 13:27:27,398 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 13:27:27,450 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:27:28,568 INFO usb_comm 542: Device not connected
2019-01-10 13:27:28,569 INFO amp_gui 200: failed connection
2019-01-10 13:27:28,578 INFO usb_comm 542: Device not connected
2019-01-10 13:27:28,578 INFO amp_gui 200: failed connection
2019-01-10 13:27:28,680 INFO usb_comm 542: Device not connected
2019-01-10 13:27:28,680 INFO amp_gui 200: failed connection
2019-01-10 13:27:28,855 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 13:27:28,898 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 13:27:29,907 INFO usb_comm 542: Device not connected
2019-01-10 13:27:29,907 INFO amp_gui 200: failed connection
2019-01-10 13:27:29,917 INFO usb_comm 542: Device not connected
2019-01-10 13:27:29,917 INFO amp_gui 200: failed connection
2019-01-10 13:27:30,019 INFO usb_comm 542: Device not connected
2019-01-10 13:27:30,019 INFO amp_gui 200: failed connection
2019-01-10 14:07:27,956 INFO usb_comm 74: attempting connection
2019-01-10 14:07:27,957 INFO usb_comm 223: Device not found
2019-01-10 14:07:27,957 INFO usb_comm 84: not found
2019-01-10 14:07:28,033 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:07:28,085 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:07:29,201 INFO usb_comm 542: Device not connected
2019-01-10 14:07:29,201 INFO amp_gui 200: failed connection
2019-01-10 14:07:29,211 INFO usb_comm 542: Device not connected
2019-01-10 14:07:29,211 INFO amp_gui 200: failed connection
2019-01-10 14:07:29,312 INFO usb_comm 542: Device not connected
2019-01-10 14:07:29,312 INFO amp_gui 200: failed connection
2019-01-10 14:07:29,493 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:07:29,538 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:07:30,548 INFO usb_comm 542: Device not connected
2019-01-10 14:07:30,548 INFO amp_gui 200: failed connection
2019-01-10 14:07:30,559 INFO usb_comm 542: Device not connected
2019-01-10 14:07:30,559 INFO amp_gui 200: failed connection
2019-01-10 14:07:30,658 INFO usb_comm 542: Device not connected
2019-01-10 14:07:30,658 INFO amp_gui 200: failed connection
2019-01-10 14:08:38,709 INFO usb_comm 74: attempting connection
2019-01-10 14:08:38,709 INFO usb_comm 223: Device not found
2019-01-10 14:08:38,709 INFO usb_comm 84: not found
2019-01-10 14:08:38,803 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:08:38,868 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:08:40,005 INFO usb_comm 542: Device not connected
2019-01-10 14:08:40,006 INFO amp_gui 200: failed connection
2019-01-10 14:08:40,016 INFO usb_comm 542: Device not connected
2019-01-10 14:08:40,016 INFO amp_gui 200: failed connection
2019-01-10 14:08:40,117 INFO usb_comm 542: Device not connected
2019-01-10 14:08:40,117 INFO amp_gui 200: failed connection
2019-01-10 14:08:40,292 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:08:40,335 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:08:41,345 INFO usb_comm 542: Device not connected
2019-01-10 14:08:41,345 INFO amp_gui 200: failed connection
2019-01-10 14:08:41,355 INFO usb_comm 542: Device not connected
2019-01-10 14:08:41,355 INFO amp_gui 200: failed connection
2019-01-10 14:08:41,457 INFO usb_comm 542: Device not connected
2019-01-10 14:08:41,457 INFO amp_gui 200: failed connection
2019-01-10 14:10:25,676 INFO usb_comm 74: attempting connection
2019-01-10 14:10:25,677 INFO usb_comm 223: Device not found
2019-01-10 14:10:25,677 INFO usb_comm 84: not found
2019-01-10 14:10:25,755 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:10:25,806 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:10:26,915 INFO usb_comm 542: Device not connected
2019-01-10 14:10:26,915 INFO amp_gui 200: failed connection
2019-01-10 14:10:26,926 INFO usb_comm 542: Device not connected
2019-01-10 14:10:26,926 INFO amp_gui 200: failed connection
2019-01-10 14:10:27,026 INFO usb_comm 542: Device not connected
2019-01-10 14:10:27,026 INFO amp_gui 200: failed connection
2019-01-10 14:10:27,204 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:10:27,250 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:10:28,263 INFO usb_comm 542: Device not connected
2019-01-10 14:10:28,263 INFO amp_gui 200: failed connection
2019-01-10 14:10:28,273 INFO usb_comm 542: Device not connected
2019-01-10 14:10:28,273 INFO amp_gui 200: failed connection
2019-01-10 14:10:28,374 INFO usb_comm 542: Device not connected
2019-01-10 14:10:28,374 INFO amp_gui 200: failed connection
2019-01-10 14:11:13,163 INFO usb_comm 74: attempting connection
2019-01-10 14:11:13,164 INFO usb_comm 223: Device not found
2019-01-10 14:11:13,164 INFO usb_comm 84: not found
2019-01-10 14:11:13,239 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:11:13,288 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:11:14,395 INFO usb_comm 542: Device not connected
2019-01-10 14:11:14,395 INFO amp_gui 200: failed connection
2019-01-10 14:11:14,407 INFO usb_comm 542: Device not connected
2019-01-10 14:11:14,407 INFO amp_gui 200: failed connection
2019-01-10 14:11:14,507 INFO usb_comm 542: Device not connected
2019-01-10 14:11:14,507 INFO amp_gui 200: failed connection
2019-01-10 14:11:14,686 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:11:14,732 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:11:15,744 INFO usb_comm 542: Device not connected
2019-01-10 14:11:15,744 INFO amp_gui 200: failed connection
2019-01-10 14:11:15,755 INFO usb_comm 542: Device not connected
2019-01-10 14:11:15,755 INFO amp_gui 200: failed connection
2019-01-10 14:11:15,855 INFO usb_comm 542: Device not connected
2019-01-10 14:11:15,855 INFO amp_gui 200: failed connection
2019-01-10 14:12:43,571 INFO usb_comm 74: attempting connection
2019-01-10 14:12:43,572 INFO usb_comm 223: Device not found
2019-01-10 14:12:43,572 INFO usb_comm 84: not found
2019-01-10 14:12:43,648 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:12:43,698 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:12:44,812 INFO usb_comm 542: Device not connected
2019-01-10 14:12:44,812 INFO amp_gui 200: failed connection
2019-01-10 14:12:44,822 INFO usb_comm 542: Device not connected
2019-01-10 14:12:44,822 INFO amp_gui 200: failed connection
2019-01-10 14:12:44,923 INFO usb_comm 542: Device not connected
2019-01-10 14:12:44,923 INFO amp_gui 200: failed connection
2019-01-10 14:12:45,095 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:12:45,138 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:12:46,154 INFO usb_comm 542: Device not connected
2019-01-10 14:12:46,154 INFO amp_gui 200: failed connection
2019-01-10 14:12:46,164 INFO usb_comm 542: Device not connected
2019-01-10 14:12:46,164 INFO amp_gui 200: failed connection
2019-01-10 14:12:46,266 INFO usb_comm 542: Device not connected
2019-01-10 14:12:46,266 INFO amp_gui 200: failed connection
2019-01-10 14:13:45,270 INFO usb_comm 74: attempting connection
2019-01-10 14:13:45,272 INFO usb_comm 223: Device not found
2019-01-10 14:13:45,272 INFO usb_comm 84: not found
2019-01-10 14:13:45,348 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:13:45,400 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:13:46,515 INFO usb_comm 542: Device not connected
2019-01-10 14:13:46,515 INFO amp_gui 200: failed connection
2019-01-10 14:13:46,526 INFO usb_comm 542: Device not connected
2019-01-10 14:13:46,526 INFO amp_gui 200: failed connection
2019-01-10 14:13:46,627 INFO usb_comm 542: Device not connected
2019-01-10 14:13:46,627 INFO amp_gui 200: failed connection
2019-01-10 14:13:46,805 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:13:46,848 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:13:47,864 INFO usb_comm 542: Device not connected
2019-01-10 14:13:47,864 INFO amp_gui 200: failed connection
2019-01-10 14:13:47,875 INFO usb_comm 542: Device not connected
2019-01-10 14:13:47,875 INFO amp_gui 200: failed connection
2019-01-10 14:13:47,976 INFO usb_comm 542: Device not connected
2019-01-10 14:13:47,976 INFO amp_gui 200: failed connection
2019-01-10 14:14:01,079 INFO usb_comm 74: attempting connection
2019-01-10 14:14:01,079 INFO usb_comm 223: Device not found
2019-01-10 14:14:01,079 INFO usb_comm 84: not found
2019-01-10 14:14:01,079 INFO amp_gui 197: No Device detected
2019-01-10 14:15:02,897 INFO usb_comm 74: attempting connection
2019-01-10 14:15:07,447 INFO usb_comm 223: Device not found
2019-01-10 14:15:07,447 INFO usb_comm 84: not found
2019-01-10 14:15:07,530 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:15:07,582 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:15:08,815 INFO usb_comm 542: Device not connected
2019-01-10 14:15:08,815 INFO amp_gui 200: failed connection
2019-01-10 14:15:08,825 INFO usb_comm 542: Device not connected
2019-01-10 14:15:08,825 INFO amp_gui 200: failed connection
2019-01-10 14:15:08,926 INFO usb_comm 542: Device not connected
2019-01-10 14:15:08,926 INFO amp_gui 200: failed connection
2019-01-10 14:15:09,101 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:15:09,144 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:15:10,275 INFO usb_comm 542: Device not connected
2019-01-10 14:15:10,275 INFO amp_gui 200: failed connection
2019-01-10 14:15:10,285 INFO usb_comm 542: Device not connected
2019-01-10 14:15:10,285 INFO amp_gui 200: failed connection
2019-01-10 14:15:10,384 INFO usb_comm 542: Device not connected
2019-01-10 14:15:10,384 INFO amp_gui 200: failed connection
2019-01-10 14:15:17,670 INFO usb_comm 74: attempting connection
2019-01-10 14:31:48,078 INFO usb_comm 74: attempting connection
2019-01-10 14:33:39,908 INFO usb_comm 74: attempting connection
2019-01-10 14:35:19,308 INFO usb_comm 74: attempting connection
2019-01-10 14:36:02,092 INFO usb_comm 74: attempting connection
2019-01-10 14:37:20,302 INFO usb_comm 74: attempting connection
2019-01-10 14:39:51,111 INFO usb_comm 74: attempting connection
2019-01-10 14:40:04,247 INFO usb_comm 74: attempting connection
2019-01-10 14:41:19,594 INFO usb_comm 74: attempting connection
2019-01-10 14:41:33,421 INFO usb_comm 230: Device not found
2019-01-10 14:41:33,421 INFO usb_comm 84: not found
2019-01-10 14:41:33,502 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:41:33,552 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:41:34,775 INFO usb_comm 549: Device not connected
2019-01-10 14:41:34,775 INFO amp_gui 200: failed connection
2019-01-10 14:41:34,785 INFO usb_comm 549: Device not connected
2019-01-10 14:41:34,785 INFO amp_gui 200: failed connection
2019-01-10 14:41:34,884 INFO usb_comm 549: Device not connected
2019-01-10 14:41:34,884 INFO amp_gui 200: failed connection
2019-01-10 14:41:35,063 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:41:35,108 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:41:36,243 INFO usb_comm 549: Device not connected
2019-01-10 14:41:36,243 INFO amp_gui 200: failed connection
2019-01-10 14:41:36,253 INFO usb_comm 549: Device not connected
2019-01-10 14:41:36,253 INFO amp_gui 200: failed connection
2019-01-10 14:41:36,352 INFO usb_comm 549: Device not connected
2019-01-10 14:41:36,352 INFO amp_gui 200: failed connection
2019-01-10 14:41:47,039 INFO usb_comm 74: attempting connection
2019-01-10 14:42:42,480 INFO usb_comm 74: attempting connection
2019-01-10 14:42:46,030 INFO usb_comm 230: Device not found
2019-01-10 14:42:46,030 INFO usb_comm 84: not found
2019-01-10 14:42:46,114 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:42:46,168 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:42:47,392 INFO usb_comm 549: Device not connected
2019-01-10 14:42:47,392 INFO amp_gui 200: failed connection
2019-01-10 14:42:47,404 INFO usb_comm 549: Device not connected
2019-01-10 14:42:47,404 INFO amp_gui 200: failed connection
2019-01-10 14:42:47,503 INFO usb_comm 549: Device not connected
2019-01-10 14:42:47,503 INFO amp_gui 200: failed connection
2019-01-10 14:42:47,677 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:42:47,719 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:42:48,841 INFO usb_comm 549: Device not connected
2019-01-10 14:42:48,841 INFO amp_gui 200: failed connection
2019-01-10 14:42:48,851 INFO usb_comm 549: Device not connected
2019-01-10 14:42:48,851 INFO amp_gui 200: failed connection
2019-01-10 14:42:48,951 INFO usb_comm 549: Device not connected
2019-01-10 14:42:48,951 INFO amp_gui 200: failed connection
2019-01-10 14:42:56,552 INFO usb_comm 74: attempting connection
2019-01-10 14:43:29,878 INFO usb_comm 240: PSoC amp found
2019-01-10 14:43:41,608 INFO amp_gui 186: device is connected
2019-01-10 14:43:49,000 INFO amp_gui 186: device is connected
2019-01-10 14:43:56,750 INFO amp_gui 186: device is connected
2019-01-10 14:44:01,911 INFO amp_gui 186: device is connected
2019-01-10 14:44:05,423 INFO amp_gui 186: device is connected
2019-01-10 14:44:26,358 INFO amp_gui 186: device is connected
2019-01-10 14:44:38,342 INFO amp_gui 186: device is connected
2019-01-10 14:44:47,694 INFO amp_gui 186: device is connected
2019-01-10 14:45:01,946 INFO usb_comm 74: attempting connection
2019-01-10 14:45:01,946 INFO usb_comm 230: Device not found
2019-01-10 14:45:01,946 INFO usb_comm 84: not found
2019-01-10 14:45:02,023 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 14:45:02,073 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:45:03,187 INFO usb_comm 549: Device not connected
2019-01-10 14:45:03,187 INFO amp_gui 200: failed connection
2019-01-10 14:45:03,197 INFO usb_comm 549: Device not connected
2019-01-10 14:45:03,197 INFO amp_gui 200: failed connection
2019-01-10 14:45:03,296 INFO usb_comm 549: Device not connected
2019-01-10 14:45:03,296 INFO amp_gui 200: failed connection
2019-01-10 14:45:03,474 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 14:45:03,519 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 14:45:04,529 INFO usb_comm 549: Device not connected
2019-01-10 14:45:04,529 INFO amp_gui 200: failed connection
2019-01-10 14:45:04,540 INFO usb_comm 549: Device not connected
2019-01-10 14:45:04,540 INFO amp_gui 200: failed connection
2019-01-10 14:45:04,641 INFO usb_comm 549: Device not connected
2019-01-10 14:45:04,641 INFO amp_gui 200: failed connection
2019-01-10 14:45:11,559 INFO usb_comm 74: attempting connection
2019-01-10 14:45:11,559 INFO usb_comm 230: Device not found
2019-01-10 14:45:11,559 INFO usb_comm 84: not found
2019-01-10 14:45:11,559 INFO amp_gui 197: No Device detected
2019-01-10 14:45:23,927 INFO usb_comm 74: attempting connection
2019-01-10 14:45:23,930 INFO usb_comm 240: PSoC amp found
2019-01-10 15:06:30,269 INFO usb_comm 74: attempting connection
2019-01-10 15:06:30,270 INFO usb_comm 226: Device not found
2019-01-10 15:06:30,270 INFO usb_comm 84: not found
2019-01-10 15:06:30,348 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:06:30,398 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:06:31,509 INFO usb_comm 545: Device not connected
2019-01-10 15:06:31,509 INFO amp_gui 199: failed connection
2019-01-10 15:06:31,519 INFO usb_comm 545: Device not connected
2019-01-10 15:06:31,519 INFO amp_gui 199: failed connection
2019-01-10 15:06:31,619 INFO usb_comm 545: Device not connected
2019-01-10 15:06:31,619 INFO amp_gui 199: failed connection
2019-01-10 15:06:31,792 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:06:31,835 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:06:32,842 INFO usb_comm 545: Device not connected
2019-01-10 15:06:32,842 INFO amp_gui 199: failed connection
2019-01-10 15:06:32,851 INFO usb_comm 545: Device not connected
2019-01-10 15:06:32,851 INFO amp_gui 199: failed connection
2019-01-10 15:06:32,951 INFO usb_comm 545: Device not connected
2019-01-10 15:06:32,951 INFO amp_gui 199: failed connection
2019-01-10 15:06:42,592 INFO usb_comm 74: attempting connection
2019-01-10 15:06:42,595 INFO usb_comm 236: PSoC amp found
2019-01-10 15:07:32,678 INFO amp_gui 185: device is connected
2019-01-10 15:07:35,881 INFO amp_gui 185: device is connected
2019-01-10 15:07:38,009 INFO amp_gui 185: device is connected
2019-01-10 15:07:40,321 INFO amp_gui 185: device is connected
2019-01-10 15:18:56,720 INFO usb_comm 74: attempting connection
2019-01-10 15:18:56,721 INFO usb_comm 226: Device not found
2019-01-10 15:18:56,721 INFO usb_comm 84: not found
2019-01-10 15:18:56,806 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:18:56,864 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:18:57,979 INFO usb_comm 545: Device not connected
2019-01-10 15:18:57,979 INFO amp_gui 199: failed connection
2019-01-10 15:18:57,989 INFO usb_comm 545: Device not connected
2019-01-10 15:18:57,989 INFO amp_gui 199: failed connection
2019-01-10 15:18:58,089 INFO usb_comm 545: Device not connected
2019-01-10 15:18:58,089 INFO amp_gui 199: failed connection
2019-01-10 15:18:58,263 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:18:58,308 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:18:59,315 INFO usb_comm 545: Device not connected
2019-01-10 15:18:59,315 INFO amp_gui 199: failed connection
2019-01-10 15:18:59,326 INFO usb_comm 545: Device not connected
2019-01-10 15:18:59,326 INFO amp_gui 199: failed connection
2019-01-10 15:18:59,427 INFO usb_comm 545: Device not connected
2019-01-10 15:18:59,427 INFO amp_gui 199: failed connection
2019-01-10 15:20:17,766 INFO usb_comm 74: attempting connection
2019-01-10 15:20:17,767 INFO usb_comm 226: Device not found
2019-01-10 15:20:17,767 INFO usb_comm 84: not found
2019-01-10 15:20:17,844 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:20:17,895 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:20:18,996 INFO usb_comm 545: Device not connected
2019-01-10 15:20:18,996 INFO amp_gui 199: failed connection
2019-01-10 15:20:19,006 INFO usb_comm 545: Device not connected
2019-01-10 15:20:19,006 INFO amp_gui 199: failed connection
2019-01-10 15:20:19,108 INFO usb_comm 545: Device not connected
2019-01-10 15:20:19,108 INFO amp_gui 199: failed connection
2019-01-10 15:20:19,282 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:20:19,325 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:20:46,131 INFO usb_comm 545: Device not connected
2019-01-10 15:20:46,131 INFO amp_gui 199: failed connection
2019-01-10 15:20:46,142 INFO usb_comm 545: Device not connected
2019-01-10 15:20:46,142 INFO amp_gui 199: failed connection
2019-01-10 15:20:47,259 INFO usb_comm 545: Device not connected
2019-01-10 15:20:47,259 INFO amp_gui 199: failed connection
2019-01-10 15:24:06,351 INFO usb_comm 74: attempting connection
2019-01-10 15:24:06,351 INFO usb_comm 226: Device not found
2019-01-10 15:24:06,351 INFO usb_comm 84: not found
2019-01-10 15:24:06,427 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:24:06,477 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:24:07,592 INFO usb_comm 545: Device not connected
2019-01-10 15:24:07,592 INFO amp_gui 199: failed connection
2019-01-10 15:24:07,601 INFO usb_comm 545: Device not connected
2019-01-10 15:24:07,601 INFO amp_gui 199: failed connection
2019-01-10 15:24:07,703 INFO usb_comm 545: Device not connected
2019-01-10 15:24:07,703 INFO amp_gui 199: failed connection
2019-01-10 15:24:07,877 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:24:07,920 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:24:10,516 INFO usb_comm 545: Device not connected
2019-01-10 15:24:10,516 INFO amp_gui 199: failed connection
2019-01-10 15:24:10,526 INFO usb_comm 545: Device not connected
2019-01-10 15:24:10,526 INFO amp_gui 199: failed connection
2019-01-10 15:24:10,627 INFO usb_comm 545: Device not connected
2019-01-10 15:24:10,627 INFO amp_gui 199: failed connection
2019-01-10 15:24:56,115 INFO usb_comm 74: attempting connection
2019-01-10 15:24:56,115 INFO usb_comm 226: Device not found
2019-01-10 15:24:56,117 INFO usb_comm 84: not found
2019-01-10 15:24:56,191 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:24:56,240 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:24:57,351 INFO usb_comm 545: Device not connected
2019-01-10 15:24:57,351 INFO amp_gui 199: failed connection
2019-01-10 15:24:57,361 INFO usb_comm 545: Device not connected
2019-01-10 15:24:57,361 INFO amp_gui 199: failed connection
2019-01-10 15:24:57,461 INFO usb_comm 545: Device not connected
2019-01-10 15:24:57,461 INFO amp_gui 199: failed connection
2019-01-10 15:24:57,634 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:24:57,678 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:24:58,684 INFO usb_comm 545: Device not connected
2019-01-10 15:24:58,684 INFO amp_gui 199: failed connection
2019-01-10 15:24:58,697 INFO usb_comm 545: Device not connected
2019-01-10 15:24:58,697 INFO amp_gui 199: failed connection
2019-01-10 15:24:58,798 INFO usb_comm 545: Device not connected
2019-01-10 15:24:58,798 INFO amp_gui 199: failed connection
2019-01-10 15:30:38,588 INFO usb_comm 74: attempting connection
2019-01-10 15:30:38,588 INFO usb_comm 226: Device not found
2019-01-10 15:30:38,588 INFO usb_comm 84: not found
2019-01-10 15:30:38,673 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:30:38,727 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:30:39,831 INFO usb_comm 545: Device not connected
2019-01-10 15:30:39,831 INFO amp_gui 199: failed connection
2019-01-10 15:30:39,841 INFO usb_comm 545: Device not connected
2019-01-10 15:30:39,841 INFO amp_gui 199: failed connection
2019-01-10 15:30:39,941 INFO usb_comm 545: Device not connected
2019-01-10 15:30:39,941 INFO amp_gui 199: failed connection
2019-01-10 15:33:12,517 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:33:12,588 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:33:38,305 INFO usb_comm 74: attempting connection
2019-01-10 15:33:38,305 INFO usb_comm 226: Device not found
2019-01-10 15:33:38,305 INFO usb_comm 84: not found
2019-01-10 15:33:38,381 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:33:38,433 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:33:39,539 INFO usb_comm 545: Device not connected
2019-01-10 15:33:39,539 INFO amp_gui 199: failed connection
2019-01-10 15:33:39,549 INFO usb_comm 545: Device not connected
2019-01-10 15:33:39,549 INFO amp_gui 199: failed connection
2019-01-10 15:33:39,650 INFO usb_comm 545: Device not connected
2019-01-10 15:33:39,650 INFO amp_gui 199: failed connection
2019-01-10 15:34:17,816 INFO usb_comm 74: attempting connection
2019-01-10 15:34:17,818 INFO usb_comm 226: Device not found
2019-01-10 15:34:17,818 INFO usb_comm 84: not found
2019-01-10 15:34:21,608 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:34:21,667 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:34:22,910 INFO usb_comm 545: Device not connected
2019-01-10 15:34:22,910 INFO amp_gui 199: failed connection
2019-01-10 15:34:22,920 INFO usb_comm 545: Device not connected
2019-01-10 15:34:22,920 INFO amp_gui 199: failed connection
2019-01-10 15:34:23,019 INFO usb_comm 545: Device not connected
2019-01-10 15:34:23,019 INFO amp_gui 199: failed connection
2019-01-10 15:34:40,687 INFO usb_comm 74: attempting connection
2019-01-10 15:34:40,687 INFO usb_comm 226: Device not found
2019-01-10 15:34:40,687 INFO usb_comm 84: not found
2019-01-10 15:34:55,022 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:34:55,099 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:35:13,757 INFO usb_comm 74: attempting connection
2019-01-10 15:35:13,757 INFO usb_comm 226: Device not found
2019-01-10 15:35:13,757 INFO usb_comm 84: not found
2019-01-10 15:35:20,285 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:35:52,325 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:36:34,038 INFO usb_comm 74: attempting connection
2019-01-10 15:36:34,039 INFO usb_comm 226: Device not found
2019-01-10 15:36:34,039 INFO usb_comm 84: not found
2019-01-10 15:36:36,928 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:36:36,980 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:36:38,184 INFO usb_comm 545: Device not connected
2019-01-10 15:36:38,184 INFO amp_gui 199: failed connection
2019-01-10 15:36:38,196 INFO usb_comm 545: Device not connected
2019-01-10 15:36:38,196 INFO amp_gui 199: failed connection
2019-01-10 15:36:38,296 INFO usb_comm 545: Device not connected
2019-01-10 15:36:38,296 INFO amp_gui 199: failed connection
2019-01-10 15:36:40,301 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage19" as iconphoto: not a photo image
2019-01-10 15:36:40,342 INFO tkinter_pyplot 70: setting xlim (low, high): 1, 128
2019-01-10 15:36:41,446 INFO usb_comm 545: Device not connected
2019-01-10 15:36:41,446 INFO amp_gui 199: failed connection
2019-01-10 15:36:41,456 INFO usb_comm 545: Device not connected
2019-01-10 15:36:41,456 INFO amp_gui 199: failed connection
2019-01-10 15:36:41,556 INFO usb_comm 545: Device not connected
2019-01-10 15:36:41,556 INFO amp_gui 199: failed connection
2019-01-10 15:38:02,394 INFO usb_comm 74: attempting connection
2019-01-10 15:38:02,397 INFO usb_comm 236: PSoC amp found
2019-01-10 15:40:21,424 INFO usb_comm 545: Device not connected
2019-01-10 15:40:21,424 INFO amp_gui 199: failed connection
2019-01-10 15:40:21,436 INFO usb_comm 545: Device not connected
2019-01-10 15:40:21,436 INFO amp_gui 199: failed connection
2019-01-10 15:41:11,881 INFO amp_gui 185: device is connected
2019-01-10 15:41:18,184 INFO amp_gui 185: device is connected
2019-01-10 15:43:32,951 INFO usb_comm 74: attempting connection
2019-01-10 15:43:32,951 INFO usb_comm 226: Device not found
2019-01-10 15:43:32,953 INFO usb_comm 84: not found
2019-01-10 15:43:35,934 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
2019-01-10 15:43:35,984 INFO tkinter_pyplot 70: setting xlim (low, high): 20, 200
2019-01-10 15:43:37,203 INFO usb_comm 545: Device not connected
2019-01-10 15:43:37,203 INFO amp_gui 199: failed connection
2019-01-10 15:43:37,213 INFO usb_comm 545: Device not connected
2019-01-10 15:43:37,213 INFO amp_gui 199: failed connection
2019-01-10 15:43:37,313 INFO usb_comm 545: Device not connected
2019-01-10 15:43:37,313 INFO amp_gui 199: failed connection
2019-01-10 15:43:37,490 INFO _backend_tk 1060: Could not load matplotlib icon: can't use "pyimage18" as iconphoto: not a photo image
2019-01-10 15:43:37,535 INFO tkinter_pyplot 70: setting xlim (low, high): 20, 200
2019-01-10 15:43:38,670 INFO usb_comm 545: Device not connected
2019-01-10 15:43:38,670 INFO amp_gui 199: failed connection
2019-01-10 15:43:38,680 INFO usb_comm 545: Device not connected
2019-01-10 15:43:38,680 INFO amp_gui 199: failed connection
2019-01-10 15:43:38,780 INFO usb_comm 545: Device not connected
2019-01-10 15:43:38,780 INFO amp_gui 199: failed connection
2019-01-10 15:43:50,424 INFO usb_comm 74: attempting connection
2019-01-10 15:43:50,427 INFO usb_comm 236: PSoC amp found
2019-01-10 15:44:36,357 INFO usb_comm 545: Device not connected
2019-01-10 15:44:36,357 INFO amp_gui 199: failed connection
2019-01-10 15:44:36,368 INFO usb_comm 545: Device not connected
2019-01-10 15:44:36,368 INFO amp_gui 199: failed connection
2019-01-10 15:44:45,276 INFO usb_comm 545: Device not connected
2019-01-10 15:44:45,276 INFO amp_gui 199: failed connection
2019-01-10 15:44:45,286 INFO usb_comm 545: Device not connected
2019-01-10 15:44:45,286 INFO amp_gui 199: failed connection
2019-01-10 15:45:54,960 INFO amp_gui 185: device is connected
2019-01-10 15:45:58,025 INFO amp_gui 185: device is connected
2019-01-10 15:46:02,167 INFO amp_gui 185: device is connected
2019-01-10 15:47:06,789 INFO amp_gui 185: device is connected
